http:
  routers:
    gateway-https:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - websecure
      tls: {}
      service: gateway
    gateway-on-frontend:
      rule: "(Host(`localhost`) || Host(`127.0.0.1`)) && PathPrefix(`/api`)"
      entryPoints:
        - websecure-frontend
      tls: {}
      service: gateway
      middlewares:
        - api-strip-prefix
      priority: 100
    frontend-https:
      rule: "Host(`localhost`) || Host(`127.0.0.1`)"
      entryPoints:
        - websecure-frontend
      tls: {}
      service: frontend

  middlewares:
    api-strip-prefix:
      stripPrefix:
        prefixes:
          - /api

  services:
    gateway:
      loadBalancer:
        servers:
          - url: "http://api-gateway:3000"
    frontend:
      loadBalancer:
        servers:
          - url: "http://frontend:3000"

tls:
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem