entrypoints:
  web:
    address: ":80"
    http:
      redirections:
        entrypoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
  websecure-frontend:
    address: ":5173"

providers:
  file:
    filename: /traefik/dynamic.yml
    watch: true

log:
  level: DEBUG